name: Check Schema
on:
  pull_request:
    paths:
      - "snowplow/schemas/**"
    branches: [main]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Show github ref
        shell: bash
        run: echo ${GITHUB_REF}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Output values
        shell: bash
        run: |
          echo "${{ steps.extract_branch.outputs.branch }}"
