name: Check Schema
on:
  pull_request:
    paths:
      - "snowplow/schemas/**"
    branches: [main]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Output values
        shell: bash
        run: |
          echo "${{ github.event.pull_request.head.sha }}"
