name: Check Schema
on:
  pull_request:
    paths:
      - "snowplow/schemas/**"
    branches: [main]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # 0 indicates all history for all branches. 
          # Source: https://github.com/marketplace/actions/checkout
          fetch-depth: 0
      
      - name: Get changed schemas
        id: get-changed-schemas
        shell: bash
        run: |
          git diff origin/main...${{ github.event.pull_request.head.sha }} --name-status --relative=snowplow/schemas/ > changed-schemas.txt
          echo "FILE_NAME=changed-schemas.txt" >> $GITHUB_OUTPUT
        
      - name: Print changed schemas
        shell: bash
        run: |
          echo "List of changed-schema file names:"
          echo "${{ steps.get-changed-schemas.outputs.FILE_NAME }}"
          cat changed-schemas.txt
