name: A workflow for my Hello World file
on: workflow_dispatch
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: Print event_name
        run: |
          echo "${{ github.event_name }}"

  embed:
    uses: aovalle-hc/hello-github-actions/.github/workflows/main.yml@main
    needs: build
